### ISSUE TITLE
Support for vcf files using the csi index

### ISSUE THREAD

**Issue by ctsa** [Sentieon/hap-eval#11]
Hi, Great tool! Could Sentieon vcflib also support csi-indexed vcf files?

**Comment by DonFreed** [comment]
This is now supported in `main`. Please let me know if you have any issues.

**Comment by ctsa** [comment]
Thanks for the quick feature @DonFreed ! I'll give it a try by this afternoon.

**Comment by ctsa** [comment]
Confirmed this edit works for all the csi cases I've tried. Thank you!
