### ISSUE TITLE
Understanding hap_eval results on latest combined small and large variant GIAB T2T benchmark

### ISSUE THREAD

**Issue by ctsa** [Sentieon/hap-eval#14]
The latest GIAB draft T2T [benchmark](https://ftp-trace.ncbi.nlm.nih.gov/ReferenceSamples/giab/data/AshkenazimTrio/analysis/NIST_HG002_DraftBenchmark_defrabbV0.015-20240215) has shifted to a single VCF combining small and structural variants.

I've noticed that `hap_eval`'s assessment of a given SV sample is substantially impacted by shifting to this new benchmark. I demonstrate the effect below on one public example VCF, but a similar trend appears with other SV callers and sequencing inputs. If we download an example SV VCF and the last two versions of the GIAB T2T draft benchmark as follows:

```
# Example SV VCF
wget https://downloads.pacbcloud.com/public/revio/2022Q4/HG002-rep1/analysis/HG002.m84011_220902_175841_s1.GRCh38.pbsv.vcf.gz
wget https://downloads.pacbcloud.com/public/revio/2022Q4/HG002-rep1/analysis/HG002.m84011_220902_175841_s1.GRCh38.pbsv.vcf.gz.tbi

# 20231107 T2T benchmark
wget -P NIST_HG002_DraftBenchmark_defrabbV0.012-20231107 https://ftp-trace.ncbi.nlm.nih.gov/ReferenceSamples/giab/data/AshkenazimTrio/analysis/NIST_HG002_DraftBenchmark_defrabbV0.012-20231107/GRCh38_HG002-T2TQ100-V1.0_stvar.vcf.gz
wget -P NIST_HG002_DraftBenchmark_defrabbV0.012-20231107 https://ftp-trace.ncbi.nlm.nih.gov/ReferenceSamples/giab/data/AshkenazimTrio/analysis/NIST_HG002_DraftBenchmark_defrabbV0.012-20231107/GRCh38_HG002-T2TQ100-V1.0_stvar.vcf.gz.tbi
wget -P NIST_HG002_DraftBenchmark_defrabbV0.012-20231107 https://ftp-trace.ncbi.nlm.nih.gov/ReferenceSamples/giab/data/AshkenazimTrio/analysis/NIST_HG002_DraftBenchmark_defrabbV0.012-20231107/GRCh38_HG002-T2TQ100-V1.0_stvar.benchmark.bed

# 20240215 T2T benchmark
wget -P NIST_HG002_DraftBenchmark_defrabbV0.015-20240215 https://ftp-trace.ncbi.nlm.nih.gov/ReferenceSamples/giab/data/AshkenazimTrio/analysis/NIST_HG002_DraftBenchmark_defrabbV0.015-20240215/GRCh38_HG2-T2TQ100-V1.0.vcf.gz
wget -P NIST_HG002_DraftBenchmark_defrabbV0.015-20240215 https://ftp-trace.ncbi.nlm.nih.gov/ReferenceSamples/giab/data/AshkenazimTrio/analysis/NIST_HG002_DraftBenchmark_defrabbV0.015-20240215/GRCh38_HG2-T2TQ100-V1.0.vcf.gz.tbi
wget -P NIST_HG002_DraftBenchmark_defrabbV0.015-20240215 https://ftp-trace.ncbi.nlm.nih.gov/ReferenceSamples/giab/data/AshkenazimTrio/analysis/NIST_HG002_DraftBenchmark_defrabbV0.015-20240215/GRCh38_HG2-T2TQ100-V1.0_stvar.benchmark.bed
```

Then given a `hap_eval` cmdline similar to this for each case:
```
hap_eval \
  --reference /path/to/GRCh38.fasta \
  --base NIST_HG002_DraftBenchmark_defrabbV0.012-20231107/GRCh38_HG002-T2TQ100-V1.0_stvar.vcf.gz \
  --interval NIST_HG002_DraftBenchmark_defrabbV0.012-20231107/GRCh38_HG002-T2TQ100-V1.0_stvar.benchmark.bed \
  --comp HG002.m84011_220902_175841_s1.GRCh38.pbsv.vcf.gz \
  --thread_count 8 >| t2t_20231107.stdout
```

The previous and latest GIAB T2T draft benchmark results are:
```
$ tail -2 t2t_20231107.stdout
Counter({'MM': 19571, 'MX': 920, 'FP': 579, 'FN': 550, '??': 139, 'XX': 71})
precision 0.9197 recall 0.9209 f1 0.9203
$ tail -2 t2t_20240215.stdout 
Counter({'MM': 20364, 'MX': 402, 'FN': 360, '??': 146, 'XX': 39, 'FP': 10})
precision 0.9715 recall 0.9556 f1 0.9635
```

I'd like to get some insight as to whether the assessment on the newest benchmark should still be considered valid, or if this single-VCF benchmark format is interfering with `hap_eval`'s design in a way that's biasing the result.

**Comment by nate-d-olson** [comment]
@ctsa we have found including small variants in the sv benchmark vcf improves variant comparisons which probably accounts for at least some of the performance improvements you are experiencing. We also made a number of changes to how the benchmark regions are defined, see text from the README, https://ftp-trace.ncbi.nlm.nih.gov/ReferenceSamples/giab/data/AshkenazimTrio/analysis/NIST_HG002_DraftBenchmark_defrabbV0.015-20240215/README.md, below. I assume these are responsible for the bulk of the difference in performance between the 20231107 and 20240215 versions of the benchmark. 

```
- A single vcf is provided for small and structural variant benchmark sets and should be used for benchmarking either small and structural variants.
- This version of the benchmark now merges segdups and satellites within 40kb before checking if the assembly has any breaks in the alignment inside the repeat regions, so that it more conservatively excludes nearby satellites and segdups if there is a break in the alignment inside a satellite or segdup.
- Fixed issue with code not excluding dip.bed edges as intended.
- VDJ excluded from small variant and structural variant benchmark regions.
```

**Comment by ctsa** [comment]
Thanks for pointing out these details @nate-d-olson. It will be great if the benchmark improvements explain at least some of the difference, but it's such a large change that it would be helpful to know if this shift in format would be expected to violate assumptions in hap_eval's design, etc. I won't have time to directly look at the shifted FP/FN cases for a bit so this would be helpful in deciding whether to transition to the new format.

**Comment by DonFreed** [comment]
The inclusion of SNVs and indels into the benchmark VCF will affect `hap_eval`'s assessment. We can see this by filtering small events from benchmark VCF (with `bcftools view -i '(ILEN >= 50 || ILEN <= 50)'`).

Here is my evaluation using original 20240215 VCF:
```txt
Counter({'MM': 20325, 'MX': 425, 'FN': 360, '??': 146, 'XX': 55, 'FP': 10})
precision 0.9697 recall 0.9537 f1 0.9616
```

And after bcftools to remove SNVs/indels:
```txt
Counter({'MM': 20395, 'MX': 981, 'FN': 483, '??': 134, 'XX': 126, 'FP': 30})
precision 0.9413 recall 0.9221 f1 0.9316
```

The 20231107 VCF produces the same results with or without the bcftools filter:
```txt
Counter({'MM': 19062, 'MX': 1303, 'FP': 579, 'FN': 550, 'XX': 197, '??': 139})
precision 0.8958 recall 0.8970 f1 0.8964
```

`hap-eval` will exclude small variants after clustering, which allow the small variants to contribute to a larger SV. Additionally, this allows multiple small events to be combine to match a larger event.


Including smaller events has a few different effects on the overall evaluation:
* The size of some clusters will be extended due to nearby small variants, without including another nearby SV. This adds to the denominator of the difference threshold, changing some borderline cases from `MX` or `XX` to `MM`.
* Small variants can "bridge" nearby SVs into larger clusters. This is why the total number of evaluated clusters is reduced when small variants are included as multiple SVs are included in a larger cluster. This reduces the number of `FP` and `FN` calls.
* Small variants can make some clusters too complex, resulting in warnings for `too many phasing combos` and increasing the number of `??` clusters.

**Comment by ctsa** [comment]
Thanks @DonFreed! I think I understand how to interpret the assessment differences with small variants now.
