### ISSUE TITLE
Output insufficiently described

### ISSUE THREAD

**Issue by archmageirvine** [Sentieon/hap-eval#4]
Is there a description of the output somewhere?

I was expecting to see some kind of count of true-positives and false-positives (presumably these numbers are computed at some point since you have f1).

What is "MM" ?

**Comment by DonFreed** [comment]
Apologies for the delay here. This information is now added to the README: https://github.com/Sentieon/hap-eval/blob/main/README.md#interpreting-the-output.

Let me know if you have any questions about the output that is not addressed in the updated README.
