### ISSUE TITLE
invalid literal for int() with base 10

### ISSUE THREAD

**Issue by yaningyang** [Sentieon/hap-eval#8]
ValueError: ("invalid literal for int() with base 10: '.'", 'chr1\t10397\tcuteSV.INS.0\tC\tCCCTAAACCTCACCCCCACCCCCACCCCACCCCACCCCAACCCCA\t.\tPASS\tPRECISE;SVTYPE=INS;SVLEN=44;END=10397;CIPOS=-49,49;CILEN=-11,11;RE=16;RNAMES=NULL\tGT:DR:DV:PL:GQ\t./.:.:16:.,.,.:.')

**Comment by DonFreed** [comment]
Thank you for opening this issue. This was fixed in vcflib at, https://github.com/Sentieon/vcflib/commit/39c476e441296ec64ea28a939cbd0ae5dc6b7358. Updating the vcflib submodule should fix the error.

**Comment by DonFreed** [comment]
This should be fixed after #9. Please update to the latest commit and try again.
